---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: clusterrolebinding
    app.kubernetes.io/instance: gateway-rolebinding
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: netcon-problem-management-subsystem
    app.kubernetes.io/part-of: netcon-problem-management-subsystem
    app.kubernetes.io/managed-by: kustomize
  name: gateway-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gateway-role
subjects:
- kind: ServiceAccount
  name: gateway
  namespace: system
