---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: gateway-role
rules:
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
- apiGroups:
  - netcon.janog.gr.jp
  resources:
  - problemenvironments
  verbs:
  - get
  - list
  - watch
  - delete
- apiGroups:
  - netcon.janog.gr.jp
  resources:
  - problemenvironments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - netcon.janog.gr.jp
  resources:
  - problems
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - netcon.janog.gr.jp
  resources:
  - problems/status
  verbs:
  - get
- apiGroups:
  - netcon.janog.gr.jp
  resources:
  - workers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
