resources:
- role_binding.yaml
- role.yaml
- scheduler.yaml
- service_account.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: scheduler 
  newName: proelbtn/netcon-pms-scheduler
  newTag: dev
