apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler
  namespace: system
  labels:
    control-plane: scheduler
    app.kubernetes.io/name: deployment
    app.kubernetes.io/instance: scheduler
    app.kubernetes.io/component: scheduler
    app.kubernetes.io/created-by: netcon-problem-management-subsystem
    app.kubernetes.io/part-of: netcon-problem-management-subsystem
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    matchLabels:
      control-plane: scheduler
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: scheduler
      labels:
        control-plane: scheduler
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - command:
        - /scheduler
        args:
        - --leader-elect
        image: scheduler:latest
        imagePullPolicy: Always
        name: scheduler
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - "ALL"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
      serviceAccountName: scheduler
      terminationGracePeriodSeconds: 10
