---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: serviceaccount
    app.kuberentes.io/instance: scheduler
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: netcon-problem-management-subsystem
    app.kubernetes.io/part-of: netcon-problem-management-subsystem
    app.kubernetes.io/managed-by: kustomize
  name: scheduler
  namespace: system
