/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkersIndexRouteImport } from './routes/workers/index'
import { Route as ProblemsIndexRouteImport } from './routes/problems/index'
import { Route as ProblemEnvironmentsIndexRouteImport } from './routes/problem-environments/index'
import { Route as WorkersWorkerNameRouteImport } from './routes/workers/$workerName'
import { Route as ProblemsProblemNameRouteImport } from './routes/problems/$problemName'
import { Route as ProblemEnvironmentsEnvNameRouteImport } from './routes/problem-environments/$envName'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkersIndexRoute = WorkersIndexRouteImport.update({
  id: '/workers/',
  path: '/workers/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemsIndexRoute = ProblemsIndexRouteImport.update({
  id: '/problems/',
  path: '/problems/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemEnvironmentsIndexRoute =
  ProblemEnvironmentsIndexRouteImport.update({
    id: '/problem-environments/',
    path: '/problem-environments/',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkersWorkerNameRoute = WorkersWorkerNameRouteImport.update({
  id: '/workers/$workerName',
  path: '/workers/$workerName',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemsProblemNameRoute = ProblemsProblemNameRouteImport.update({
  id: '/problems/$problemName',
  path: '/problems/$problemName',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemEnvironmentsEnvNameRoute =
  ProblemEnvironmentsEnvNameRouteImport.update({
    id: '/problem-environments/$envName',
    path: '/problem-environments/$envName',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/problem-environments/$envName': typeof ProblemEnvironmentsEnvNameRoute
  '/problems/$problemName': typeof ProblemsProblemNameRoute
  '/workers/$workerName': typeof WorkersWorkerNameRoute
  '/problem-environments/': typeof ProblemEnvironmentsIndexRoute
  '/problems/': typeof ProblemsIndexRoute
  '/workers/': typeof WorkersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/problem-environments/$envName': typeof ProblemEnvironmentsEnvNameRoute
  '/problems/$problemName': typeof ProblemsProblemNameRoute
  '/workers/$workerName': typeof WorkersWorkerNameRoute
  '/problem-environments': typeof ProblemEnvironmentsIndexRoute
  '/problems': typeof ProblemsIndexRoute
  '/workers': typeof WorkersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/problem-environments/$envName': typeof ProblemEnvironmentsEnvNameRoute
  '/problems/$problemName': typeof ProblemsProblemNameRoute
  '/workers/$workerName': typeof WorkersWorkerNameRoute
  '/problem-environments/': typeof ProblemEnvironmentsIndexRoute
  '/problems/': typeof ProblemsIndexRoute
  '/workers/': typeof WorkersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/problem-environments/$envName'
    | '/problems/$problemName'
    | '/workers/$workerName'
    | '/problem-environments/'
    | '/problems/'
    | '/workers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/problem-environments/$envName'
    | '/problems/$problemName'
    | '/workers/$workerName'
    | '/problem-environments'
    | '/problems'
    | '/workers'
  id:
    | '__root__'
    | '/'
    | '/problem-environments/$envName'
    | '/problems/$problemName'
    | '/workers/$workerName'
    | '/problem-environments/'
    | '/problems/'
    | '/workers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProblemEnvironmentsEnvNameRoute: typeof ProblemEnvironmentsEnvNameRoute
  ProblemsProblemNameRoute: typeof ProblemsProblemNameRoute
  WorkersWorkerNameRoute: typeof WorkersWorkerNameRoute
  ProblemEnvironmentsIndexRoute: typeof ProblemEnvironmentsIndexRoute
  ProblemsIndexRoute: typeof ProblemsIndexRoute
  WorkersIndexRoute: typeof WorkersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workers/': {
      id: '/workers/'
      path: '/workers'
      fullPath: '/workers/'
      preLoaderRoute: typeof WorkersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problems/': {
      id: '/problems/'
      path: '/problems'
      fullPath: '/problems/'
      preLoaderRoute: typeof ProblemsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problem-environments/': {
      id: '/problem-environments/'
      path: '/problem-environments'
      fullPath: '/problem-environments/'
      preLoaderRoute: typeof ProblemEnvironmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workers/$workerName': {
      id: '/workers/$workerName'
      path: '/workers/$workerName'
      fullPath: '/workers/$workerName'
      preLoaderRoute: typeof WorkersWorkerNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problems/$problemName': {
      id: '/problems/$problemName'
      path: '/problems/$problemName'
      fullPath: '/problems/$problemName'
      preLoaderRoute: typeof ProblemsProblemNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problem-environments/$envName': {
      id: '/problem-environments/$envName'
      path: '/problem-environments/$envName'
      fullPath: '/problem-environments/$envName'
      preLoaderRoute: typeof ProblemEnvironmentsEnvNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProblemEnvironmentsEnvNameRoute: ProblemEnvironmentsEnvNameRoute,
  ProblemsProblemNameRoute: ProblemsProblemNameRoute,
  WorkersWorkerNameRoute: WorkersWorkerNameRoute,
  ProblemEnvironmentsIndexRoute: ProblemEnvironmentsIndexRoute,
  ProblemsIndexRoute: ProblemsIndexRoute,
  WorkersIndexRoute: WorkersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
