---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: netcon
  name: pro-001 
data:
  manifest.yml: |
    topology:
      nodes:
        n1:
          kind: linux
          image: alpine:latest
        n2:
          kind: linux
          image: alpine:latest
      links:
        - endpoints: ["n1:eth1","n2:eth1"]
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: netcon
  name: pro-002
data:
  manifest.yml: |
    topology:
      nodes:
        n1:
          kind: linux
          image: nicolaka/netshoot:latest
        n2:
          kind: linux
          image: nicolaka/netshoot:latest
      links:
        - endpoints: ["n1:eth1","n2:eth1"]
---
apiVersion: netcon.janog.gr.jp/v1alpha1
kind: ProblemEnvironment
metadata:
  namespace: netcon
  name: pro-001-a0e832
spec:
  topologyFile:
    configMapRef:
      name: pro-001
      key: manifest.yml
---
apiVersion: netcon.janog.gr.jp/v1alpha1
kind: ProblemEnvironment
metadata:
  namespace: netcon
  name: pro-001-c9f16h
spec:
  topologyFile:
    configMapRef:
      name: pro-001
      key: manifest.yml
---
apiVersion: netcon.janog.gr.jp/v1alpha1
kind: ProblemEnvironment
metadata:
  namespace: netcon
  name: pro-002-b3f8ba
spec:
  topologyFile:
    configMapRef:
      name: pro-002
      key: manifest.yml
---
apiVersion: netcon.janog.gr.jp/v1alpha1
kind: ProblemEnvironment
metadata:
  namespace: netcon
  name: pro-002-afb81d
spec:
  topologyFile:
    configMapRef:
      name: pro-002
      key: manifest.yml
