apiVersion: netcon.janog.gr.jp/v1alpha1
kind: Problem
metadata:
  labels:
    app.kubernetes.io/name: problem
    app.kubernetes.io/instance: problem-sample
    app.kubernetes.io/part-of: netcon-problem-management-subsystem
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: netcon-problem-management-subsystem
  name: problem-sample
spec:
  # TODO(user): Add fields here
