---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: netcon
  name: problemenvironment001
data:
  manifest.yml: |
    name: problemenvironment001
    topology:
      nodes:
        n1:
          kind: linux
          image: alpine:latest
        n2:
          kind: linux
          image: alpine:latest
      links:
        - endpoints: ["n1:eth1","n2:eth1"]
---
apiVersion: netcon.janog.gr.jp/v1alpha1
kind: ProblemEnvironment
metadata:
  namespace: netcon
  name: problemenvironment001
spec:
  topologyFile:
    configMapRef:
      name: problemenvironment001
      key: manifest.yml