---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: netcon
  name: pro-001
data:
  manifest.yml: |
    topology:
      nodes:
        n1:
          kind: linux
          image: alpine:latest
        n2:
          kind: linux
          image: alpine:latest
      links:
        - endpoints: ["n1:eth1","n2:eth1"]
---
apiVersion: netcon.janog.gr.jp/v1alpha1
kind: Problem
metadata:
  namespace: netcon
  name: pro-001
spec:
  assignableReplicas: 8
  template:
    spec:
      topologyFile:
        configMapRef:
          name: pro-001
          key: manifest.yml

