---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: netcon
  name: pro-001 
data:
  manifest.yml: |
    topology:
      nodes:
        n1:
          kind: linux
          image: alpine:latest
        n2:
          kind: linux
          image: alpine:latest
      links:
        - endpoints: ["n1:eth1","n2:eth1"]
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: netcon
  name: pro-002
data:
  manifest.yml: |
    topology:
      nodes:
        n1:
          kind: linux
          image: nicolaka/netshoot:latest
          binds:
          - ./resolv.conf:/etc/resolv.conf:ro
        n2:
          kind: linux
          image: nicolaka/netshoot:latest
          binds:
          - ./resolv.conf:/etc/resolv.conf:ro
      links:
        - endpoints: ["n1:eth1","n2:eth1"]
  resolv.conf: |
    nameserver 1.1.1.1
---
apiVersion: netcon.janog.gr.jp/v1alpha1
kind: ProblemEnvironment
metadata:
  namespace: netcon
  name: pro-001-a0e832
spec:
  files:
    configMapRef:
      name: pro-001
---
apiVersion: netcon.janog.gr.jp/v1alpha1
kind: ProblemEnvironment
metadata:
  namespace: netcon
  name: pro-001-c9f16h
spec:
  files:
    configMapRef:
      name: pro-001
---
apiVersion: netcon.janog.gr.jp/v1alpha1
kind: ProblemEnvironment
metadata:
  namespace: netcon
  name: pro-002-b3f8ba
spec:
  files:
    configMapRef:
      name: pro-002
---
apiVersion: netcon.janog.gr.jp/v1alpha1
kind: ProblemEnvironment
metadata:
  namespace: netcon
  name: pro-002-afb81d
spec:
  files:
    configMapRef:
      name: pro-002
