apiVersion: netcon.janog.gr.jp/v1alpha1
kind: ProblemEnvironment
metadata:
  labels:
    app.kubernetes.io/name: problemenvironment
    app.kubernetes.io/instance: problemenvironment-sample
    app.kubernetes.io/part-of: netcon-problem-management-subsystem
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: netcon-problem-management-subsystem
  name: problemenvironment-sample
spec:
  # TODO(user): Add fields here
